apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-data
  namespace: lightwell-demo
  labels:
    app: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: lightwell-demo
  labels:
    app: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
